### ISSUE TITLE
copysign

### ISSUE THREAD

**Issue by edwilliams16** [mwganson/Parametric_Curve_FP#10]
Any chance you could add copysign to your functions?

`copysign: lambda a, b: math.copysign(a,b)`

_a*b/abs(b)_  has to be special-cased for b = 0

**Comment by edwilliams16** [comment]
I found you have the sgn() function already - but not documented.  copysign(a, b) is supposedly preferred for IEEE reasons

[https://stackoverflow.com/questions/1986152/why-doesnt-python-have-a-sign-function/1986776#1986776](url)

**Comment by mwganson** [comment]
Sure.  Can you submit a PR?  Don't forget to update the version, too.  And if you want to update the readme for the documentation, that would be good, too.

**Comment by edwilliams16** [comment]
Done - I think.

**Comment by mwganson** [comment]
Merged.  Please update via the addon manager and test the functionality.  Thanks for the PR.

**Comment by edwilliams16** [comment]
I had a struggle getting addon manager to upgrade the Macro.  I'm not sure whether

- I needed to have refreshed the local cache first
- The problem was my installed version was already the new one

I eventually got there , but I'm not sure what went wrong on the way.  When I tried to upgrade, addon manager said the earlier version was current.


<img width="875" alt="Screenshot 2023-05-07 at 7 48 12 AM" src="https://user-images.githubusercontent.com/18408746/236694768-11b52008-fda1-432a-a48d-c215eb7808ec.png">

Now it says:
<img width="874" alt="Screenshot 2023-05-07 at 8 08 03 AM" src="https://user-images.githubusercontent.com/18408746/236694985-843da268-1aac-4acc-8be1-def792007001.png">

 I don't know how "check for updates" is supposed to work.  What is it comparing?

**Comment by mwganson** [comment]
I thought about that after posting.  You were already up to date locally.  I was able to update via addon manager, but I did have to refresh the local cache.  It had been a while since I had updated on the wiki, but I think I did it right.  The actual code for the macro is hosted as a gist on gist.github.com.  The gist has to be updated, which I do manually via copy and paste, and then the link from the wiki has to be updated to point to the new macro code url, which changes on each update.  There are 2 url's on the wiki, one for the user to manually download, and the other the addon manager uses.
